### ISSUE TITLE
playbook.predeploy.yml is configured to deploy to <path>/app

### ISSUE THREAD

**Issue by malakai97** [mlibrary/ansible-predeploy#3]
The extra folder is unnecessary and misleading. 

We should investigate why this was used on legacy code.  

It's probably best to resolve this issue before any rollout, because at that point Pandora's box will be open.

**Comment by aelkiss** [comment]
Right. If you look at the layout of things under `/www`, this might be more clear - the assumption at the time was one application per virtual host, and a desire for a consistent layout under the top level vhost with things like `log`, `web`, etc. I agree it's better just to have the Capistrano `current`, `releases`, and `shared` directories at the top level rather than under `app` - I agree it will be less confusing, and almost certainly if you had a reason to have other non-Capistrano-managed things under that directory, you're doing something wrong.

**Comment by grosscol** [comment]
Addressed by commit 2808b3
